### ISSUE TITLE
Org-wide configuration

### ISSUE THREAD

**Issue by pavelzw** [prefix-dev/reproducible-builds#176]
It would be cool to be able to scan all repositories within an org for recipes. Something like this in `config.yaml` could be interesting:

```yml
org:
  name: my-org
  recipe-path: conda.recipe/recipe.yaml
```

This would scan all repos from `my-org` and if the repo has `conda.recipe/recipe.yaml` it would test reproducibility for this repo.
Maybe an additional configuration file for rattler-build CLI args could be interesting as well 🤔
